{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "expense-tracker.backendName" . }}-secret
  labels:
    {{- include "expense-tracker.labels" . | nindent 4 }} # <-- FIX: Changed indent to nindent
type: Opaque
data:
  DB_PASSWORD: {{ .Values.backend.secret.DB_PASSWORD | b64enc }}
  JWT_SECRET: {{ .Values.backend.secret.JWT_SECRET | b64enc }}
  SMTP_PASSWORD: {{ .Values.backend.secret.SMTP_PASSWORD | b64enc }}
  REDIS_PASSWORD: {{ .Values.backend.secret.REDIS_PASSWORD | b64enc }}
  ELASTICSEARCH_PASSWORD: {{ .Values.backend.secret.ELASTICSEARCH_PASSWORD | b64enc }}
{{- end }}