FROM python:3.11-alpine AS base
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1
WORKDIR /app

FROM base AS build
RUN apk add --no-cache \
    gcc \
    musl-dev \
    build-base \
    libffi-dev \
    mariadb-connector-c-dev
COPY requirements.txt .
RUN pip install --prefix=/install --no-cache-dir -r requirements.txt

FROM base AS runner
COPY --from=build /install /usr/local
COPY . .
EXPOSE 5000
CMD ["gunicorn", "app:create_app()", "--bind", "0.0.0.0:5000", "--workers", "2", "--threads", "2"]