apiVersion: v1
kind: Secret
metadata:
  name: employee-database-credentials
  namespace: employee-management-app
type: Opaque
data:
  # Replace these with base64-encoded values
  # echo -n 'employeeapplicationuser' | base64
  username: ZW1wbG95ZWVhcHBsaWNhdGlvbnVzZXI=
  # echo -n 'applicationPassword1234' | base64
  password: YXBwbGljYXRpb25QYXNzd29yZDEyMzQ=
  #echo -n "dev-rds.cfs8gai6czog.ap-south-1.rds.amazonaws.com:3306" | base64 
  host: ZGV2LXJkcy5jZnM4Z2FpNmN6b2cuYXAtc291dGgtMS5yZHMuYW1hem9uYXdzLmNvbTozMzA2
  #echo -n "employeedb" | base64
  database: ZW1wbG95ZWVkYg==