{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "expense-tracker.postgresName" . }}-secret
  labels:
    {{ include "expense-tracker.labels" . | nindent 4 }}
type: Opaque
data:
  postgresUser: {{ .Values.postgres.secret.postgresUser | b64enc }}
  postgresPassword: {{ .Values.postgres.secret.postgresPassword | b64enc }}
  dbUsername: {{ .Values.postgres.secret.dbUsername | b64enc }}
  dbPassword: {{ .Values.postgres.secret.dbPassword | b64enc }}
{{- end }}
