{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "expense-tracker.postgresName" . }}
  labels:
    {{ include "expense-tracker.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "expense-tracker.postgresName" . }}
  replicas: {{ .Values.postgres.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "expense-tracker.postgresName" . }}
  template:
    metadata:
      labels:
        app: {{ include "expense-tracker.postgresName" . }}
    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "expense-tracker.postgresName" . }}-secret
                  key: postgresUser
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "expense-tracker.postgresName" . }}-secret
                  key: postgresPassword
            - name: POSTGRES_DB
              value: postgres
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgres-pvc
              mountPath: /var/lib/postgresql/data
            - name: postgres-init-script
              mountPath: /docker-entrypoint-initdb.d
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - $(POSTGRES_USER)
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - $(POSTGRES_USER)
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: postgres-init-script
          configMap:
            name: {{ include "expense-tracker.postgresName" . }}-config
  volumeClaimTemplates:
    - metadata:
        name: postgres-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.postgres.storage.size }}
        storageClassName: {{ .Values.postgres.storage.storageClassName }}
{{- end }}
