{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "expense-tracker.postgresName" . }}-service
  labels:
    {{ include "expense-tracker.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "expense-tracker.postgresName" . }}
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
{{- end }}
